### PR TITLE
Linak similator api integration

### PR DESCRIPTION
**Pull request by nicki419**
Also fixes some general issues in the solution like shared objects and the .env references.

### CODE REVIEW

**Review by Tokushiro — APPROVED** [review]
When i pass Linak table object with GUID that's not in the API it throws error.
Aside from that everything works well

**Comment by nicki419** [comment]
> When i pass Linak table object with GUID that's not in the API it throws error. Aside from that everything works well

Fixed with commit 03f477ca52268a3da7eaf843fc9d4ac3f6278d93

**Comment by nicki419** [comment]
Changes based on what we discussed turned out to be quite extensive.
@Tokushiro I will need you to review again.

**Review by Tokushiro — APPROVED** [review]
It's fine after improvements 👍

**Pull request merged**
